### PR TITLE
1119 - Confirm password in registration field is now required

### LINKED ISSUE #1119: [Bug] confirm password field in registration is not required
**Describe the bug**
You can register without filing anything in confirm password field. It does its job only if you fill something.

**Expected behavior**
If the confirm password field is empty, there should be some error message and you should not be able to register without filling it.

### PR DESCRIPTION
**Pull request by jozef-drabik**
Now when someone want to register and they dont fill up confirmation password, it will throw error message for users.

Closes #1119 

## Screenshots:
Before:
image
After:
image
After:
image

http://localhost:3040/en/register

### Steps to test
Get on registration page: http://localhost:3040/en/register.
Try to fill up form without confirm password field.
Click on register button.

### Affected urls
http://localhost:3040/en/register

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

**Review by ani-kalpachka — CHANGES_REQUESTED** [review]
Do you think it would be better to use confirmPassword in order to avoid passing as string?

File: src/components/auth/register/RegisterForm.tsx [hunk 1]
```diff
@@ -33,7 +34,10 @@ const validationSchema: yup.SchemaOf<RegisterFormData> = yup
     lastName: name.required(),
     email: email.required(),
     password: password.required(),
-    'confirm-password': yup.string().oneOf([yup.ref('password')], 'validation:password-match'),
+    'confirm-password': yup
```
Comment (kachar) [inline src/components/auth/register/RegisterForm.tsx:37]: Let's use `confirmPassword` instead of kebab cased name. Just like `lastName`

Comment (kachar) [reply src/components/auth/register/RegisterForm.tsx:37]: See 

https://github.com/podkrepi-bg/frontend/blob/df9850f26818e8a6b7c6125285920ace898e0d04/src/components/auth/changePassword/ChangePasswordForm.tsx#L29-L33

Comment (kachar) [reply src/components/auth/register/RegisterForm.tsx:37]: @jozef-drabik Since we use this functionality in more than one place it's gonna be appropriate to extract it to the common validators at: https://github.com/podkrepi-bg/frontend/blob/8dc9da1b0ca7994dfef6f07ce2402f972fa8df83/src/common/form/validation.ts

Comment (jan-fbc) [reply src/components/auth/register/RegisterForm.tsx]: i used camelCase now for confirmPassword as well and functionality is extracted in form/validation.ts

Comment (jozef-drabik) [reply src/components/auth/register/RegisterForm.tsx]: i used camelCase now for confirmPassword as well and functionality is extracted in form/validation.ts

**Comment by kachar** [comment]
@jozef-drabik The build seems to be failling in the CI since there's one more register form that needs to be adjusted:

https://github.com/podkrepi-bg/frontend/blob/a19a6c6db21a25bb4c47242d0224fe3db2818f89/src/components/one-time-donation/RegisterDialog.tsx#L22-L29

Looks like we need to add the `confirmPassword` validation there as well.

We also need to add one additional field:

```tsx
<PasswordField name="registerPassword" autoComplete="new-password" />
<PasswordField name="confirmPassword" autoComplete="confirm-password" />
```

**Comment by jozef-drabik** [comment]
@kachar I am sorry, it should work now. I ran build to see if there are more errors.

**Review by kachar — APPROVED** [review]
