### PR TITLE
Bugfix/On mobile device the campaign title is huge

### LINKED ISSUE #1405: [Campaigns] On mobile device the campaign title is huge
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Mobile layout, Campaigns

### Describe the Bug

The campaign's title on mobile should be 2rem (32px) and now it's 2.8125rem (45px) :

image

### To Reproduce

1. Open podkrepi.bg on a mobile device
2. Select any campaign from the list with campaigns
3. On the Campaign details page you will see that the font size of the campaign's title is huge

### Expected Behavior

The campaign's title should be 2rem (32px) :

image

### Which browser are you using? (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by mm-hstefanova**
Update the font size of the campaign title to 32px for mobile view

Closes #1405

## Screenshots:

BEFORE:
image

AFTER:

image

## List of pages that are affected by the changes 
Campaign Details page

## Environment
Local

### CODE REVIEW

**Review by ani-kalpachka — APPROVED** [review]

File: src/components/client/campaigns/CampaignDetails.tsx [hunk 1]
```diff
@@ -53,11 +53,13 @@ const StyledGrid = styled(Grid)(({ theme }) => ({
 
     [theme.breakpoints.up('xs')]: {
```
Comment (sashko9807) [inline src/components/client/campaigns/CampaignDetails.tsx:54]: This breakpoint seems redundant to me.  Can you try, setting the `fontSize` and `marginBottom` properties without it, and see if it works? 
The text should still be 32px on viewports smaller than 900px, and 45px on viewports bigger than 900px.

**Review by sashko9807 — COMMENTED** [review]
@ani-kalpachka everything seems ok to me.

**Comment by ani-kalpachka** [comment]
@mm-hstefanova nice update! :rocket:
