### PR TITLE
Save donation flow inside sessionStorage

### LINKED ISSUE #1260: [Bug] Login with Google returns user to step 1 again during the donation process.
### Which area(s) of Podkrepi.bg are affected?

Donation

### Describe the Bug

When I initiate a donation before being logged:

1. I input the donation amount. (step 1)
2. I login via Google
3. I have to input the donation amount again (step 1)

### To Reproduce

1. Initiate a donation without being logged in
2. Login via Google

### Expected Behavior

When I initiate a donation before being logged in:

1. I input the donation amount. (step 1)
2. I login via Google
3. Step 2

### Which browser are you using? (if relevant)

Safari Version 15.5

### PR DESCRIPTION
**Pull request by sashko9807**
Saves the selected values from formik inside sessionStorage, to prevent data loss, on page reload/refresh.
The values are saved until either successful donation has been made, or until the browser tab has been closed.

Closes #1260 

### Steps to test
1. Select campaign, and click Donate buton.
2. Complete a few donation steps, and reload the page.
3. The selected values from donation flow, should be saved

### CODE REVIEW

File: src/components/client/one-time-donation/helpers/donateSession.ts [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+  values: OneTimeDonation
+  step: number
+}
+
+function createSessionObject(
+  campaignSlug: string,
+  values: OneTimeDonation,
+  step: number,
+): DonationSession {
+  const donationSession = sessionStorage.getItem(PREFIX + campaignSlug)
```
Comment (igoychev) [inline src/components/client/one-time-donation/helpers/donateSession.ts:16]: good call to add the campaign slug as key!

**Review by igoychev — APPROVED** [review]
tested the session locally and works well, merging now to test on dev
