### PR TITLE
1247-Fix main menu donate button routing.

### LINKED ISSUE #1247: [Bug] English version state is not preserved when open the Campaigns page by click Donate button from the header navigation
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns

### Describe the Bug

- This issue is visible **only** (as far as I see) when trying to open the Campaigns page by clicking `DONATE` button from the **HEADER navigation** into tag `header`. The `HREF` attribute value is **not changed** to `/en/campaigns` when the language is changed. 

- The additional `Donate` button on the body into tag `section` is fine. 

### To Reproduce

1. Open the Home page
2. Change the language from the Header navigation to EN
3. Click `Donate` button from the Header navigation
4. Check the Campaigns page

**Actual result**: The language is BG

### Expected Behavior

The language version is preserved. 

### Which browser are you using? (if relevant)

Chrome 108.0.5359.99

### PR DESCRIPTION
**Pull request by Katzarov**
Closes #1247

## Motivation and context 

Use a different button component that can handle locales when routing. Now, clicking on the donate button, correctly preserves the already selected local (BG or EN) in the route. 
There were slight changes to the styling of the button, remedied most important ones by using some inline styles. 

## Screenshots:

Before|After
---|---
image|image

## Testing

- When BG lang is selected, clicking on the Donate button routes to correct page in BG lang.
- When EN lang is selected, clicking on the Donate button routes to correct page in EN lang.

### Affected urls

http://localhost:3040/campaigns
http://localhost:3040/en/campaigns

### New or updated dependencies: none

### CODE REVIEW

File: src/components/layout/nav/MainNavMenu.tsx [hunk 1]
```diff
@@ -1,25 +1,29 @@
...
-        <Button
+        <LinkButton
           variant="outlined"
+          size="large"
           color="inherit"
-          href={routes.campaigns.index}
-          style={{ borderColor: '#32A9FE' }}>
-          {t('nav.donatе')}
-        </Button>
+          style={{ borderColor: '#32A9FE' }}
```
Comment (kachar) [inline src/components/layout/nav/MainNavMenu.tsx:21]: @Katzarov Let's use `sx` instead of `style` here - it compiles the CSS as class instead of passing it inline

```suggestion
          sx={{ borderColor: '#32A9FE' }}
```

**Review by kachar — APPROVED** [review]
Nice update @Katzarov, thanks!
