### PR TITLE
Edit user profile frontend

### LINKED ISSUE #793: [Bug] [Major] Edit your profile function is not working
**Describe the bug**
Cannot use the "редактирай" function on My Profile page

**To Reproduce**

1. Go to 'Homepage'
2. Login 
3. Go to My Profile
4. Click on "редактирай"
5. See the error 

**Expected behavior**
to be allowed to edit your profile information 

**Actual behavior**
"Редактирай" button is refreshing the page

**Screenshots**
Screenshot 2022-05-26 at 15 12 42

Desktop: 
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

### PR DESCRIPTION
**Pull request by nradkova**
## Motivation and context
Closes #793 

- [x] Editing user name, email, birthday, and password in Keycloak and database.
- [x] Disabling user account in Keycloak and signing him out.
- [x] Updating user session by a new sign-in request after a successful edit query.
- [x] To be able to initialize this sign-in request, a password field is added in each modal.
- [x] Translation of ProfileInfoTab page and modals.
- [x] Updating password validation (as it is in Keycloak - 1 uppercase, 1 digit, 1 special character, 8 characters min).
- [x] Adding constraints to users logged in with google to edit their profile.

### CODE REVIEW

File: src/common/form/validation.ts [hunk 1]
```diff
@@ -62,3 +67,11 @@ export const email = string().trim().email()
 export const phone = string().trim().matches(phoneRegex, customValidators.phone).min(9).max(15)
 export const name = string().trim().matches(noNumbersRegex, customValidators.name).min(2).max(50)
 export const companyName = string().trim().min(2).max(50)
+
+// according to password policy in Keycloak- 1 uppercase, 1 digit, 1 special character, min 8 characters
+export const passwordRegex = /^(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*_.?])[A-Za-z\d!@#$%^&*_.?]{8,30}$/
```
Comment (igoychev) [inline src/common/form/validation.ts:72]: good that we're aligning the password policy with the keycloak one

File: src/common/util/useCurrentPerson.ts [hunk 2]
```diff
@@ -39,4 +40,25 @@ export function updateCurrentPerson() {
...
+
+export function disableCurrentPerson() {
+  const { data: session } = useSession()
+  return async () => {
+    return await apiClient.delete<UpdatePerson, AxiosResponse<Person>>(
+      endpoints.account.update.url,
+      authConfig(session?.accessToken),
+    )
+  }
+}
```
Comment (igoychev) [inline src/common/util/useCurrentPerson.ts:62]: Do we need this function? It will be strange for someone to want to disable his own account. A more likely action would be for an Admin to disable someone else's account - so the methog might be needed but with personId as parameter.

File: src/components/auth/profile/UpdateEmailModal.tsx [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+
+      const updateUser = await mutation.mutateAsync({
+        ...person,
+        email: values.email,
+      })
+
+      const reLogin = await signIn<'credentials'>('credentials', {
+        email: person.email,
+        password: values.password,
+        redirect: false,
```
Comment (igoychev) [inline src/components/auth/profile/UpdateEmailModal.tsx:98]: It looks the reLogin here should happen with the new email value, like this: email: values.email

**Review by igoychev — CHANGES_REQUESTED** [review]
great work overall!

**Review by igoychev — APPROVED** [review]

**Comment by igoychev** [comment]
Merging [edit-user-profile-frontend](https://github.com/podkrepi-bg/frontend/tree/edit-user-profile-frontend)
